name: "infra preview & deploy"

on:
  push:
   branches:
     - main
   pushs:
    - 10_infra/**
    - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
   name: "Preview"
   runs-on: ubuntu-22.04
   steps:
     - run: |
        echo "Hello World"
